### PR TITLE
fix: update deps and unpin was-bindgen over leptos and leptos-use

### PR DESCRIPTION
**Pull request by sabify**

### CODE REVIEW

**Comment by sabify** [comment]
Failed CIs are related to cached version of `cargo-leptos` used in workflow even though I updated it. Merging may help.

**Comment by Baptistemontan** [comment]
> Failed CIs are related to cached version of `cargo-leptos` used in workflow even though I updated it. Merging may help.

CI don't use cache, I know I should but eh, the reason is just that you did'nt update cargo-leptos for those tests, see review

**Comment by sabify** [comment]
> > Failed CIs are related to cached version of `cargo-leptos` used in workflow even though I updated it. Merging may help.
> 
> CI don't use cache, I know I should but eh, the reason is just that you did'nt update cargo-leptos for those tests, see review

There were multiple of it...

**Comment by Baptistemontan** [comment]
Thanks!

**Pull request merged**
